#!/bin/bash

# `-e` Exit on error.
# `-u` Trait unset variables as an error.
# `-o pipeline` Propagate pipeline errors.
set -euo pipefail

# Install command line tools.
if ! xcode-select -p &>/dev/null; then
  xcode-select --install
  echo "Waiting for Command Line Tools installation..."
  until xcode-select -p &>/dev/null; do sleep 5; done
fi

# Install oh-my-zsh.
if [ ! -d "${HOME}/.oh-my-zsh" ]; then
  git clone https://github.com/ohmyzsh/ohmyzsh.git "${HOME}/.oh-my-zsh"
fi

# Determine the dotfiles directory.
DOTFILES_DIRECTORY="$(git rev-parse --show-toplevel)"

# Install SSH related files
mkdir -p "${HOME}/.ssh/projects"
ln -sf "${DOTFILES_DIRECTORY}/macOS/ssh/config" "${HOME}/.ssh/config"

# Install ZSH configuration files.
zsh_files=(
  .aliases.zsh
  .functions.zsh
  .locale.zsh
  .initialize.zsh
  .zshrc
)
for file in "${zsh_files[@]}"; do
  ln -sf "${DOTFILES_DIRECTORY}/macOS/zsh/${file}" "${HOME}/${file}"
done
unset file
unset zsh_files

# Install git configuration files.
mkdir -p "${HOME}/.config/git"
if [ ! -f "${HOME}/.config/git/local.gitconfig" ]; then
  cp "${DOTFILES_DIRECTORY}/git/local.gitconfig" "${HOME}/.config/git/local.gitconfig"
fi
git_files=(
  .gitconfig
  .git-commit-message
  .gitignore_global
)
for file in "${git_files[@]}"; do
  ln -sf "${DOTFILES_DIRECTORY}/git/${file}" "${HOME}/${file}"
done
unset file
unset git_files

# Install python's startup commands.
ln -sf "${DOTFILES_DIRECTORY}/macOS/python/.pythonrc" "${HOME}/.pythonrc"

# Suppress login messages.
touch "${HOME}/.hushlogin"

# Install Brew.
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

touch ~/.zprofile
grep -qF 'eval "$(/opt/homebrew/bin/brew shellenv)"' ~/.zprofile \
  || echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

# Install applications through Brew.
brew bundle install --file="${DOTFILES_DIRECTORY}/macOS/brew/Brewfile"

# Install lazygit configuration file.
mkdir -p "${HOME}/Library/Application Support/lazygit"
ln -sf "${DOTFILES_DIRECTORY}/lazygit/config.yml" "${HOME}/Library/Application Support/lazygit/config.yml"

# Remove the need for `sudo` while installing node packages globally.
mkdir -p "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

# Install tmux configuration file.
ln -sf "${DOTFILES_DIRECTORY}/macOS/tmux/.tmux.conf" "${HOME}/.tmux.conf"

# Install tmux plugin manager.
if [ ! -d "${HOME}/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
if tmux info &>/dev/null; then
  tmux source "${HOME}/.tmux.conf"
fi

# Install NeoVim with LazyVim starter.
if [ ! -d "${HOME}/.config/nvim" ]; then
  git clone https://github.com/LazyVim/starter "${HOME}/.config/nvim"
  rm -rf "${HOME}/.config/nvim/.git"
fi
stow -d "${DOTFILES_DIRECTORY}/macOS" -t "${HOME}" nvim

# Install PHP's XDebug extension.
if ! php -m 2>/dev/null | grep -qi xdebug; then
  pecl install xdebug
fi

# Update macOS defaults.
source "${DOTFILES_DIRECTORY}/macOS/defaults"
